import { MenuItem, Category, Restaurant, ChefCollection } from '../types';

export const CATEGORIES: Category[] = [
  { id: 'all',        nameAr: 'الكل',            nameEn: 'Tout',               icon: '🍽️' },
  { id: 'signatures', nameAr: 'التوقيعات',        nameEn: 'Les Signatures',     icon: '🌯' },
  { id: 'burgers',    nameAr: 'البرغر البلدي',    nameEn: 'Beldi Burgers',      icon: '🍔' },
  { id: 'tajines',    nameAr: 'الطواجن',           nameEn: 'Les Tajines',        icon: '🥘' },
  { id: 'soupes',     nameAr: 'الشوربات',          nameEn: 'Les Soupes',         icon: '🥣' },
  { id: 'sultan',     nameAr: 'صالون الشاي',       nameEn: 'Salon de Thé',       icon: '🍵' },
  { id: 'snacks',     nameAr: 'سناكس ومينو',       nameEn: 'Snacks & Menus',     icon: '🍟' },
  { id: 'vendredi',   nameAr: 'جمعة بريستيج',      nameEn: 'Vendredi Prestige',  icon: '🕌' },
];

export const CHEF_COLLECTIONS: ChefCollection[] = [
  {
    id: 'col1',
    nameAr: 'التوقيعات الثلاث',
    nameEn: 'Les 3 Signatures',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=200&h=200&fit=crop',
    itemCount: 3,
  },
  {
    id: 'col2',
    nameAr: 'البرغر البلدي',
    nameEn: 'Beldi Burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&h=200&fit=crop',
    itemCount: 3,
  },
  {
    id: 'col3',
    nameAr: 'طواجن وشوربات',
    nameEn: 'Tajines & Soupes',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=200&h=200&fit=crop',
    itemCount: 5,
  },
  {
    id: 'col4',
    nameAr: 'صالون سلطان',
    nameEn: 'Salon Sultan',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=200&h=200&fit=crop',
    itemCount: 3,
  },
];

export const MENU_ITEMS: MenuItem[] = [

  // ── LES SIGNATURES ────────────────────────────────────────────────────────
  {
    id: 'item1',
    nameAr: 'الكالجين',
    nameEn: 'Le Caljine',
    descriptionAr: 'اندماج البيتزا والطاجين. عجينة بتوقيع زيت الزيتون وزعتر الأطلس.',
    descriptionEn: 'Fusion Pizza-Tajine. Pâte signature à l\'huile d\'olive & origan de l\'Atlas.',
    price: 39,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop',
    category: 'signatures',
    isAvailable: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 312,
    tags: ['بقري', 'دجاج', 'سمك'],
    extras: [
      { id: 'e1', nameAr: 'بقري',   nameEn: 'Bœuf',    price: 0 },
      { id: 'e2', nameAr: 'دجاج',   nameEn: 'Poulet',  price: 0 },
      { id: 'e3', nameAr: 'سمك',    nameEn: 'Poisson', price: 0 },
    ],
  },
  {
    id: 'item2',
    nameAr: 'التريدوس',
    nameEn: 'Le Tridos',
    descriptionAr: 'رول الطريد التقليدي بحبوب السمسم. يشمل: فريطوس وصلصة خضراء.',
    descriptionEn: 'Wrap Trid au sésame. Inclus : Fritatoes & Sauce verte.',
    price: 29,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    category: 'signatures',
    isAvailable: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 198,
    tags: ['سمسم', 'فريطوس', 'صلصة'],
    extras: [
      { id: 'e4', nameAr: 'سمسم',   nameEn: 'Sésame',    price: 0 },
      { id: 'e5', nameAr: 'توقيع',  nameEn: 'Signature', price: 0 },
    ],
  },
  {
    id: 'item3',
    nameAr: 'النيمستيلا',
    nameEn: 'Nemstilla',
    descriptionAr: 'نيم باستيلا في ورقة مُبَهَّرة. انفجار من الألوان والنكهات.',
    descriptionEn: 'Nems Pastilla en feuille épicée. Une explosion de couleurs.',
    price: 10,
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop',
    category: 'signatures',
    isAvailable: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 245,
    tags: ['كاري', 'بابريكا', 'فلفل'],
    extras: [
      { id: 'e6', nameAr: 'كاري',      nameEn: 'Curry',   price: 0 },
      { id: 'e7', nameAr: 'بابريكا',   nameEn: 'Paprika', price: 0 },
      { id: 'e8', nameAr: 'فلفل أحمر', nameEn: 'Piment',  price: 0 },
    ],
  },

  // ── LES BELDI BURGERS ─────────────────────────────────────────────────────
  {
    id: 'item4',
    nameAr: 'رويال بقري بالبرقوق',
    nameEn: 'Royal Bœuf Pruneaux',
    descriptionAr: 'خبز كامل بزيت الزيتون. كفتة مشوية، خوخ مجفف وفتات اللوز المحمص.',
    descriptionEn: 'Pain complet & Amandes grillées. Kefta grillée aux pruneaux.',
    price: 35,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    category: 'burgers',
    isAvailable: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 412,
    tags: ['كفتة', 'برقوق', 'لوز'],
    extras: [
      { id: 'e9',  nameAr: 'Ma3r9oTower +8DH', nameEn: 'Ma3r9oTower +8DH', price: 8 },
    ],
  },
  {
    id: 'item5',
    nameAr: 'كريسبي دجاج بالشرمولة',
    nameEn: 'Crispy Poulet Chermoula',
    descriptionAr: 'باناج سينيا والليمون المعصفر. دجاج مقرمش بصلصة الشرمولة.',
    descriptionEn: 'Panure Siniya & Citron confit. Poulet croustillant sauce chermoula.',
    price: 30,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop',
    category: 'burgers',
    isAvailable: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 287,
    tags: ['دجاج', 'شرمولة', 'مقرمش'],
    extras: [
      { id: 'e10', nameAr: 'Ma3r9oTower +8DH', nameEn: 'Ma3r9oTower +8DH', price: 8 },
    ],
  },
  {
    id: 'item6',
    nameAr: 'مارينا سمك مقرمش',
    nameEn: 'Marina Poisson Pané',
    descriptionAr: 'شرمولة حمراء وصلصة خضراء. سمك مقرمش بعجينة سينيا.',
    descriptionEn: 'Chermoula rouge & Sauce verte. Poisson pané façon Siniya.',
    price: 32,
    image: 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=400&h=300&fit=crop',
    category: 'burgers',
    isAvailable: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 189,
    tags: ['سمك', 'شرمولة', 'صلصة خضراء'],
    extras: [
      { id: 'e11', nameAr: 'Ma3r9oTower +8DH', nameEn: 'Ma3r9oTower +8DH', price: 8 },
    ],
  },

  // ── LES TAJINES ───────────────────────────────────────────────────────────
  {
    id: 'item7',
    nameAr: 'طاجين دجاج بالليمون',
    nameEn: 'Tajine Poulet Citron',
    descriptionAr: 'طاجين دجاج مغربي بالزيتون والليمون المعصفر والبهارات الخاصة.',
    descriptionEn: 'Tajine marocain au citron confit, olives & épices du chef.',
    price: 35,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop',
    category: 'tajines',
    isAvailable: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 203,
    tags: ['دجاج', 'ليمون', 'زيتون'],
    extras: [],
  },
  {
    id: 'item8',
    nameAr: 'طاجين لحم بالبرقوق',
    nameEn: 'Tajine Viande Pruneaux',
    descriptionAr: 'لحم طري مطهو ببطء مع البرقوق واللوز والعسل الطبيعي.',
    descriptionEn: 'Viande mijotée aux pruneaux, amandes & miel naturel.',
    price: 42,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop',
    category: 'tajines',
    isAvailable: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 167,
    tags: ['لحم', 'برقوق', 'عسل'],
    extras: [],
  },
  {
    id: 'item9',
    nameAr: 'طاجين سمك بالشرمولة',
    nameEn: 'Tajine Poisson Chermoula',
    descriptionAr: 'سمك طازج بالشرمولة الحمراء والخضار الموسمية.',
    descriptionEn: 'Poisson frais à la chermoula rouge & légumes de saison.',
    price: 38,
    image: 'https://images.unsplash.com/photo-1485962307416-993e145b0d0d?w=400&h=300&fit=crop',
    category: 'tajines',
    isAvailable: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 134,
    tags: ['سمك', 'شرمولة', 'خضار'],
    extras: [],
  },

  // ── LES SOUPES TRADITION ──────────────────────────────────────────────────
  {
    id: 'item10',
    nameAr: 'حريرة سينيا',
    nameEn: 'Harira Siniya',
    descriptionAr: 'حريرة مغربية أصيلة. تُقدَّم مع التمر والليمون.',
    descriptionEn: 'Harira marocaine authentique. Servie avec dattes & citron.',
    price: 12,
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&h=300&fit=crop',
    category: 'soupes',
    isAvailable: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 312,
    tags: ['حريرة', 'تمر', 'ليمون'],
    extras: [],
  },
  {
    id: 'item11',
    nameAr: 'بصارة الأطلس',
    nameEn: 'Bessara Atlas',
    descriptionAr: 'فول مطهو بالثوم وزيت الزيتون البكر. 100% طبيعي.',
    descriptionEn: 'Fèves, ail & huile d\'olive vierge. 100% naturel.',
    price: 12,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop',
    category: 'soupes',
    isAvailable: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 189,
    tags: ['فول', 'ثوم', 'زيت زيتون'],
    extras: [],
  },

  // ── SALON DE THÉ SULTAN PRESTIGE ──────────────────────────────────────────
  {
    id: 'item12',
    nameAr: 'شاي أخضر سلطان',
    nameEn: 'Thé Vert Sultan',
    descriptionAr: 'الشاي الأخضر الأصيل. شراكة سلطان للشاي.',
    descriptionEn: 'Thé vert authentique. Partenaire Sultan Tea.',
    price: 10,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',
    category: 'sultan',
    isAvailable: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 445,
    tags: ['شاي', 'سلطان', 'أخضر'],
    extras: [
      { id: 'e12', nameAr: 'سلطان أمبر',  nameEn: 'Sultan Ambar',   price: 0 },
      { id: 'e13', nameAr: 'سلطان جوهر',  nameEn: 'Sultan Jawhar',  price: 0 },
      { id: 'e14', nameAr: 'سلطان أصالة', nameEn: 'Sultan Assala',  price: 0 },
    ],
  },
  {
    id: 'item13',
    nameAr: 'سلطان بالنعناع الطازج',
    nameEn: 'Sultan Menthe Fraîche',
    descriptionAr: 'شاي سلطان بالنعناع الطازج. الطريقة المغربية الأصيلة.',
    descriptionEn: 'Sultan à la menthe fraîche. Préparation marocaine traditionnelle.',
    price: 12,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=300&fit=crop',
    category: 'sultan',
    isAvailable: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 523,
    tags: ['نعناع', 'سلطان', 'تقليدي'],
    extras: [
      { id: 'e15', nameAr: 'سلطان خيش',   nameEn: 'Sultan Khaych',  price: 2 },
      { id: 'e16', nameAr: 'سلطان الهيبة', nameEn: 'Sultan Al Hiba', price: 2 },
    ],
  },
  {
    id: 'item14',
    nameAr: 'منقوعات سلطان',
    nameEn: 'Infusions Sultan',
    descriptionAr: 'منقوعات طبيعية: إذخر، نعناع، أوريغانو، بابونج. 100% طبيعي.',
    descriptionEn: 'Infusions naturelles : Verveine, Ambre, Camomille. 100% naturel.',
    price: 15,
    image: 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=400&h=300&fit=crop',
    category: 'sultan',
    isAvailable: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 198,
    tags: ['منقوع', 'طبيعي', 'صحة'],
    extras: [
      { id: 'e17', nameAr: 'إذخر',   nameEn: 'Verveine',   price: 0 },
      { id: 'e18', nameAr: 'بابونج', nameEn: 'Camomille',  price: 0 },
      { id: 'e19', nameAr: 'نعناع',  nameEn: 'Menthe',     price: 0 },
      { id: 'e20', nameAr: 'زعتر',   nameEn: 'Origan',     price: 0 },
    ],
  },

  // ── SNACKS & MENUS ────────────────────────────────────────────────────────
  {
    id: 'item15',
    nameAr: 'الفريطوس',
    nameEn: 'Fritatoes',
    descriptionAr: 'فريتات موجية (Crinkle Cut) بتوليفة التوابل الأربعة السرية لسينيا.',
    descriptionEn: 'Frites ondulées Crinkle Cut aux 4 épices secrètes Siniya.',
    price: 10,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop',
    category: 'snacks',
    isAvailable: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 389,
    tags: ['كاري', 'فلفل', 'بابريكا', 'طبيعي'],
    extras: [
      { id: 'e21', nameAr: 'كاري',    nameEn: 'Curry',    price: 0 },
      { id: 'e22', nameAr: 'فلفل',    nameEn: 'Piment',   price: 0 },
      { id: 'e23', nameAr: 'بابريكا', nameEn: 'Paprika',  price: 0 },
      { id: 'e24', nameAr: 'طبيعي',   nameEn: 'Nature',   price: 0 },
    ],
  },
  {
    id: 'item16',
    nameAr: 'المعرقة بالجبن',
    nameEn: 'Ma3r9ocheese (Solo)',
    descriptionAr: 'قرصة بطاطس متبلة (12سم) بقلب من الجبن الذائب.',
    descriptionEn: 'Galette de pomme de terre épicée (12cm) au cœur fondant.',
    price: 15,
    image: 'https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=400&h=300&fit=crop',
    category: 'snacks',
    isAvailable: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 167,
    tags: ['جبن', 'بطاطس', 'مذاب'],
    extras: [],
  },
  {
    id: 'item17',
    nameAr: 'مينو بوب',
    nameEn: 'MENU POP',
    descriptionAr: 'تريدوس + فريطوس + مشروب. أفضل قيمة للثمن.',
    descriptionEn: 'Tridos + Fritatoes + Boisson. Le meilleur rapport qualité-prix.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    category: 'snacks',
    isAvailable: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 234,
    tags: ['مينو', 'تريدوس', 'اقتصادي'],
    extras: [],
  },
  {
    id: 'item18',
    nameAr: 'مينو الملكة',
    nameEn: 'MENU REINE',
    descriptionAr: 'برغر بلدي + فريطوس + مشروب. الوجبة الكاملة.',
    descriptionEn: 'Beldi Burger + Fritatoes + Boisson. Le repas complet.',
    price: 55,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    category: 'snacks',
    isAvailable: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 312,
    tags: ['مينو', 'برغر', 'كامل'],
    extras: [],
  },

  // ── VENDREDI PRESTIGE (Réservation) ──────────────────────────────────────
  {
    id: 'item19',
    nameAr: 'كسكس الدوكالة بعرقوب العجل',
    nameEn: 'Couscous Doukkali au Jarret de Veau',
    descriptionAr: 'أصالة الدوكالة في احترام تام للتقليد. سبعة خضار مختارة. سميد ناعم بزيت الزيتون. كل جمعة عبر الحجز في التطبيق.',
    descriptionEn: 'L\'authenticité des Doukkala dans le respect de la tradition. Sept légumes sélectionnés. Semoule fine à l\'huile d\'olive. Uniquement le Vendredi sur réservation.',
    price: 65,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    category: 'vendredi',
    isAvailable: true,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 98,
    tags: ['كسكس', 'جمعة', 'حجز مسبق'],
    extras: [],
  },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'rest1',
    nameAr: 'سينيا بريستيج - الدار البيضاء المركز',
    nameEn: 'Siniya Prestige - Casablanca Center',
    address: 'شارع محمد الخامس، الدار البيضاء',
    size: '100m2',
    franchiseeId: 'fr001',
    latitude: 33.5731,
    longitude: -7.5898,
    phone: '+212 522 123 456',
    openingHours: '09:00 - 23:00',
    isOpen: true,
  },
  {
    id: 'rest2',
    nameAr: 'سينيا بريستيج - الرباط أكدال',
    nameEn: 'Siniya Prestige - Rabat Agdal',
    address: 'شارع أبو عبيدة، أكدال، الرباط',
    size: '60m2',
    franchiseeId: 'fr002',
    latitude: 33.9716,
    longitude: -6.8498,
    phone: '+212 537 234 567',
    openingHours: '10:00 - 22:00',
    isOpen: true,
  },
  {
    id: 'rest3',
    nameAr: 'سينيا بريستيج - مراكش جليز',
    nameEn: 'Siniya Prestige - Marrakech Gueliz',
    address: 'شارع محمد السادس، جليز، مراكش',
    size: '100m2',
    franchiseeId: 'fr003',
    latitude: 31.6295,
    longitude: -7.9811,
    phone: '+212 524 345 678',
    openingHours: '09:00 - 23:30',
    isOpen: true,
  },
];
