import { MenuItem, Category, Restaurant, ChefCollection } from '../types';

export const CATEGORIES: Category[] = [
  { id: 'all', nameAr: 'الكل', nameEn: 'All', icon: '🍽️' },
  { id: 'starters', nameAr: 'المقبلات', nameEn: 'Starters', icon: '🥗' },
  { id: 'mains', nameAr: 'الأطباق الرئيسية', nameEn: 'Main Dishes', icon: '🍖' },
  { id: 'burgers', nameAr: 'البرغر', nameEn: 'Burgers', icon: '🍔' },
  { id: 'tajines', nameAr: 'الطاجين', nameEn: 'Tajines', icon: '🫕' },
  { id: 'pasta', nameAr: 'المعكرونة', nameEn: 'Pasta', icon: '🍝' },
  { id: 'wraps', nameAr: 'الرول', nameEn: 'Wraps', icon: '🌯' },
  { id: 'sides', nameAr: 'الأطباق الجانبية', nameEn: 'Sides', icon: '🍟' },
  { id: 'desserts', nameAr: 'الحلويات', nameEn: 'Desserts', icon: '🍰' },
  { id: 'drinks', nameAr: 'المشروبات', nameEn: 'Drinks', icon: '🥤' },
];

export const CHEF_COLLECTIONS: ChefCollection[] = [
  {
    id: 'col1',
    nameAr: 'مجموعة البحر',
    nameEn: 'Sea Collection',
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=200&h=200&fit=crop',
    itemCount: 6,
  },
  {
    id: 'col2',
    nameAr: 'شواء المغرب',
    nameEn: 'Moroccan Grill',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=200&h=200&fit=crop',
    itemCount: 8,
  },
  {
    id: 'col3',
    nameAr: 'طعام الشارع',
    nameEn: 'Street Food',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&h=200&fit=crop',
    itemCount: 10,
  },
  {
    id: 'col4',
    nameAr: 'حلويات الشيف',
    nameEn: 'Chef Desserts',
    image: 'https://images.unsplash.com/photo-1488477304112-4944851de03d?w=200&h=200&fit=crop',
    itemCount: 5,
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // Starters
  {
    id: 'item1',
    nameAr: 'سلطة الأفوكادو والجمبري',
    nameEn: 'Avocado & Shrimp Salad',
    descriptionAr: 'انتقال الريم والأراض في طبق واحد، سلطة طازجة بالجمبري وشرائح الأفوكادو الكريمية',
    descriptionEn: 'Fresh salad with grilled shrimp and creamy avocado slices',
    price: 85,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    category: 'starters',
    isAvailable: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 124,
    tags: ['صحي', 'خفيف', 'طازج'],
    extras: [
      { id: 'e1', nameAr: 'جمبري إضافي', nameEn: 'Extra Shrimp', price: 20 },
      { id: 'e2', nameAr: 'صلصة ليمون', nameEn: 'Lemon Sauce', price: 5 },
    ],
  },
  {
    id: 'item2',
    nameAr: 'مقبلات المعلق',
    nameEn: 'Mixed Moroccan Starters',
    descriptionAr: 'تشكيلة من المقبلات المغربية الأصيلة: الزعلوك، التكتوكة والبيصارة',
    descriptionEn: 'Selection of authentic Moroccan appetizers: Zaalouk, Taktouka and Bissara',
    price: 65,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=300&fit=crop',
    category: 'starters',
    isAvailable: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 89,
    tags: ['مغربي', 'تقليدي'],
    extras: [],
  },

  // Main Dishes
  {
    id: 'item3',
    nameAr: 'شريحة لحم بصوص الفلفل',
    nameEn: 'Steak with Pepper Sauce',
    descriptionAr: 'شريحة لحم بقري فاخر مطهوة على درجة مثالية مع صلصة الفلفل الأسود والخضار الموسمية',
    descriptionEn: 'Premium beef steak cooked to perfection with black pepper sauce and seasonal vegetables',
    price: 190,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=300&fit=crop',
    category: 'mains',
    isAvailable: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 203,
    tags: ['لحم بقري', 'فاخر', 'مشوي'],
    extras: [
      { id: 'e3', nameAr: 'صلصة فطر', nameEn: 'Mushroom Sauce', price: 15 },
      { id: 'e4', nameAr: 'بطاطس محمرة', nameEn: 'Grilled Potatoes', price: 20 },
    ],
  },
  {
    id: 'item4',
    nameAr: 'طاجين الدجاج بالزيتون',
    nameEn: 'Chicken Tajine with Olives',
    descriptionAr: 'طاجين دجاج مغربي أصيل بالزيتون والليمون المعصفر والبهارات الخاصة',
    descriptionEn: 'Authentic Moroccan chicken tajine with olives, preserved lemon and special spices',
    price: 120,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop',
    category: 'tajines',
    isAvailable: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 156,
    tags: ['مغربي', 'طاجين', 'دجاج'],
    extras: [
      { id: 'e5', nameAr: 'خبز مغربي', nameEn: 'Moroccan Bread', price: 10 },
    ],
  },
  {
    id: 'item5',
    nameAr: 'طاجين كفتة بالبيض',
    nameEn: 'Kefta Tajine with Eggs',
    descriptionAr: 'كفتة لحم مفروم بالبهارات المغربية في صلصة الطماطم مع بيض طازج',
    descriptionEn: 'Spiced minced meat kefta in tomato sauce with fresh eggs',
    price: 95,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop',
    category: 'tajines',
    isAvailable: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 98,
    tags: ['مغربي', 'طاجين', 'لحم مفروم'],
    extras: [],
  },

  // Burgers
  {
    id: 'item6',
    nameAr: 'البرغر المغربي الفاخر',
    nameEn: 'Premium Moroccan Burger',
    descriptionAr: 'لحم بقري مشوي مع تتبيلة الأطلسي الخاصة، جن إدام ذائب، وخبز الزعتر الأصيل',
    descriptionEn: 'Grilled beef with special Atlas seasoning, melted cheese, and authentic thyme bread',
    price: 85,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    category: 'burgers',
    isAvailable: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 312,
    tags: ['برغر', 'لحم بقري', 'مغربي'],
    extras: [
      { id: 'e6', nameAr: 'جبن إضافي', nameEn: 'Extra Cheese', price: 10 },
      { id: 'e7', nameAr: 'أفوكادو', nameEn: 'Avocado', price: 15 },
      { id: 'e8', nameAr: 'لحم مضاعف', nameEn: 'Double Meat', price: 30 },
    ],
  },
  {
    id: 'item7',
    nameAr: 'برغر الدجاج المقرمش',
    nameEn: 'Crispy Chicken Burger',
    descriptionAr: 'دجاج مقرمش مع صلصة الثوم والأعشاب والخضار الطازجة في خبز محمص',
    descriptionEn: 'Crispy chicken with garlic herb sauce and fresh vegetables in toasted bun',
    price: 70,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop',
    category: 'burgers',
    isAvailable: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 178,
    tags: ['برغر', 'دجاج', 'مقرمش'],
    extras: [
      { id: 'e9', nameAr: 'صلصة حارة', nameEn: 'Spicy Sauce', price: 5 },
    ],
  },

  // Pasta
  {
    id: 'item8',
    nameAr: 'مكرونة الترافل الأسود',
    nameEn: 'Black Truffle Pasta',
    descriptionAr: 'معكرونة فيتوشيني بصلصة الكريمة والترافل الأسود الفاخر ورقائق البارميزان',
    descriptionEn: 'Fettuccine pasta with cream sauce, premium black truffle and Parmesan flakes',
    price: 130,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop',
    category: 'pasta',
    isAvailable: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 145,
    tags: ['إيطالي', 'كريمي', 'ترافل'],
    extras: [
      { id: 'e10', nameAr: 'دجاج مشوي', nameEn: 'Grilled Chicken', price: 25 },
    ],
  },

  // Wraps
  {
    id: 'item9',
    nameAr: 'شاورما الدجاج المغربية',
    nameEn: 'Moroccan Chicken Shawarma',
    descriptionAr: 'شاورما دجاج متبلة بأجود البهارات المغربية، لومية منزلية، ومكللات مغربية',
    descriptionEn: 'Chicken shawarma seasoned with premium Moroccan spices, homemade pickles and toppings',
    price: 190,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop',
    category: 'wraps',
    isAvailable: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 267,
    tags: ['شاورما', 'دجاج', 'مغربي'],
    extras: [
      { id: 'e11', nameAr: 'صلصة حارة', nameEn: 'Spicy Sauce', price: 5 },
      { id: 'e12', nameAr: 'جبن إضافي', nameEn: 'Extra Cheese', price: 10 },
    ],
  },
  {
    id: 'item10',
    nameAr: 'تاكوس المغرب',
    nameEn: 'Moroccan Tacos',
    descriptionAr: 'تاكوس ضخم محشو بلحم البقر المفروم، بطاطس مقلية، دين، وصلصة حارة مغربية',
    descriptionEn: 'Large tacos stuffed with minced beef, fried potatoes, and Moroccan spicy sauce',
    price: 130,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop',
    category: 'wraps',
    isAvailable: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 198,
    tags: ['تاكوس', 'لحم بقري', 'حار'],
    extras: [],
  },

  // Sides
  {
    id: 'item11',
    nameAr: 'البطاطس المقلية بالتوابل',
    nameEn: 'Spiced Fried Potatoes',
    descriptionAr: 'بطاطس مقلية ذهبية متبلة بمزيج بهارات البيرير الحار',
    descriptionEn: 'Golden fried potatoes seasoned with special hot spice blend',
    price: 45,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop',
    category: 'sides',
    isAvailable: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 203,
    tags: ['بطاطس', 'مقلي', 'حار'],
    extras: [
      { id: 'e13', nameAr: 'صلصة إضافية', nameEn: 'Extra Sauce', price: 5 },
    ],
  },

  // Desserts
  {
    id: 'item12',
    nameAr: 'تارت التوت البري',
    nameEn: 'Wild Berry Tart',
    descriptionAr: 'تارت كريمي بالتوت البري الطازج على عجينة بريزيه محضرة يدوياً',
    descriptionEn: 'Creamy tart with fresh wild berries on handmade shortcrust pastry',
    price: 55,
    image: 'https://images.unsplash.com/photo-1488477304112-4944851de03d?w=400&h=300&fit=crop',
    category: 'desserts',
    isAvailable: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 187,
    tags: ['حلو', 'طازج', 'تارت'],
    extras: [
      { id: 'e14', nameAr: 'آيس كريم فانيليا', nameEn: 'Vanilla Ice Cream', price: 15 },
    ],
  },
  {
    id: 'item13',
    nameAr: 'كنافة بالقشطة',
    nameEn: 'Kunafa with Cream',
    descriptionAr: 'كنافة مغربية بالقشطة الطازجة والعسل الطبيعي، محضرة بطريقة تقليدية',
    descriptionEn: 'Moroccan kunafa with fresh cream and natural honey, traditionally prepared',
    price: 50,
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400&h=300&fit=crop',
    category: 'desserts',
    isAvailable: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 132,
    tags: ['حلو', 'مغربي', 'تقليدي'],
    extras: [],
  },

  // Drinks
  {
    id: 'item14',
    nameAr: 'عصير المانجو الطازج',
    nameEn: 'Fresh Mango Juice',
    descriptionAr: 'عصير مانجو طبيعي 100% بدون إضافات أو مواد حافظة',
    descriptionEn: '100% natural mango juice with no additives or preservatives',
    price: 35,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=400&h=300&fit=crop',
    category: 'drinks',
    isAvailable: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 89,
    tags: ['عصير', 'طازج', 'طبيعي'],
    extras: [],
  },
  {
    id: 'item15',
    nameAr: 'أتاي المغربي',
    nameEn: 'Moroccan Mint Tea',
    descriptionAr: 'الشاي المغربي الأصيل بالنعناع الطازج والسكر على الطريقة التقليدية',
    descriptionEn: 'Authentic Moroccan tea with fresh mint and sugar prepared traditionally',
    price: 25,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',
    category: 'drinks',
    isAvailable: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 245,
    tags: ['شاي', 'مغربي', 'تقليدي'],
    extras: [],
  },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'rest1',
    nameAr: 'سينيا بريستيج - الدار البيضاء المركز',
    nameEn: 'Siniya Prestige - Casablanca Center',
    address: 'شارع محمد الخامس، الدار البيضاء',
    size: '100m2',
    franchiseeId: 'fr001',
    latitude: 33.5731,
    longitude: -7.5898,
    phone: '+212 522 123 456',
    openingHours: '09:00 - 23:00',
    isOpen: true,
  },
  {
    id: 'rest2',
    nameAr: 'سينيا بريستيج - الرباط أكدال',
    nameEn: 'Siniya Prestige - Rabat Agdal',
    address: 'شارع أبو عبيدة، أكدال، الرباط',
    size: '60m2',
    franchiseeId: 'fr002',
    latitude: 33.9716,
    longitude: -6.8498,
    phone: '+212 537 234 567',
    openingHours: '10:00 - 22:00',
    isOpen: true,
  },
  {
    id: 'rest3',
    nameAr: 'سينيا بريستيج - مراكش جليز',
    nameEn: 'Siniya Prestige - Marrakech Gueliz',
    address: 'شارع محمد السادس، جليز، مراكش',
    size: '100m2',
    franchiseeId: 'fr003',
    latitude: 31.6295,
    longitude: -7.9811,
    phone: '+212 524 345 678',
    openingHours: '09:00 - 23:30',
    isOpen: true,
  },
];
